spring.application.name=Gerenciador
spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador_precos
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
server.port=8080
logging.level.org.springframework.security=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mateusamc100@gmail.com
spring.mail.password=xypafaqvnnlbseqf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=tru
spring.mail.properties.mail.smtp.starttls.required=true